### PR TITLE
replication: Don't respond to AppendEntries if term has changed

### LINKED ISSUE #339: Bad memory access (?) in uvClientInit
This comes from the same Jepsen run as #338, so see that issue for the test tarball. There's a core dump on n4 that seems to indicate a bad memory access inside uvClientInit, with the backtrace looking like this:

```
#6  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-vec.S:126
#7  0x00007f01d55f6f1f in uvClientInit (address=0x100 <error: Cannot access memory at address 0x100>, id=139644755084192, 
    uv=0x29b1fb0, c=0x7f0194235ef0) at src/uv_send.c:93
#8  uvGetClient (client=<synthetic pointer>, address=0x100 <error: Cannot access memory at address 0x100>, id=139644755084192, 
    uv=0x29b1fb0) at src/uv_send.c:436
#9  UvSend (io=<optimized out>, req=<optimized out>, message=<optimized out>, cb=<optimized out>) at src/uv_send.c:482
#10 0x00007f01d55e306d in sendAppendEntriesResult (r=r@entry=0x29b3ba0, result=result@entry=0x7f019f7fa770) at src/replication.c:817
#11 0x00007f01d55e38c8 in installSnapshotCb (req=<optimized out>, status=<optimized out>) at src/replication.c:1250
#12 0x00007f01d55f7a7b in uvSnapshotPutFinish (put=<optimized out>) at src/uv_snapshot.c:569
#13 uvSnapshotPutAfterWorkCb (work=<optimized out>, status=<optimized out>) at src/uv_snapshot.c:578
```

https://github.com/canonical/raft/blob/02ae98558b32feaf041315c14e1ade14bdc8cdc2/src/uv_send.c#L93

I haven't been able to correlate this with the node's log yet. Looks like a bad value for that `address` parameter.

### PR DESCRIPTION
**Pull request by cole-miller**
Another swing at fixing bad accesses to the `current_leader.address` field when a follower updates its term number while entries are being written to disk. This version is significantly simpler than the flawed #351, and I've added a test to cover the new code. Running Jepsen against this branch at https://github.com/canonical/jepsen.dqlite/pull/72 and it looks good so far.

Closes #339 

Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

File: src/replication.c [hunk 1]
```diff
@@ -911,10 +911,16 @@ static void appendFollowerCb(struct raft_io_append *req, int status)
         }
     }
 
-    if (r->state != RAFT_FOLLOWER) {
-        tracef("local server is not follower -> don't send result");
+    /* If our term number has changed since receiving these entries, current_leader
+     * might have changed as well, so don't send a response. */
+    if (r->current_term != args->term) {
```
Comment (MathieuBordere) [inline src/replication.c:916]: A node can move to `RAFT_CANDIDATE` without updating its term due to the pre-vote mechanism see
https://github.com/canonical/raft/blob/425a6b57bdea8a600402eac6ee1ab1ea97b36215/src/election.c#L122 

So probably we need something more like `r->current_term != args->term || r->state != RAFT_FOLLOWER`

File: src/replication.c [hunk 2]
```diff
@@ -911,10 +911,16 @@ static void appendFollowerCb(struct raft_io_append *req, int status)
...
+        tracef("new term since receiving entries -> don't respond");
         goto out;
     }
+    /* If our term number hasn't changed, we should still be either FOLLOWER
+     * or UNAVAILABLE -- and the latter is handled by bailing out earlier in
+     * this function. */
+    assert(r->state == RAFT_FOLLOWER);
```
Comment (MathieuBordere) [inline src/replication.c:923]: This will break to due remark above.

File: test/integration/test_replication.c [hunk 3]
```diff
@@ -1016,3 +1017,31 @@ TEST(replication, diskWriteFailure, setUp, tearDown, 0, NULL)
...
+    BOOTSTRAP_START_AND_ELECT;
+    CLUSTER_APPLY_ADD_X(0, req, 1, NULL);
+
+    /* Wait for the leader to replicate the entry */
+    CLUSTER_STEP_UNTIL_ELAPSED(500);
+
+    /* Force a new term */
+    CLUSTER_DEPOSE;
+    CLUSTER_ELECT(1);
+
```
Comment (MathieuBordere) [inline test/integration/test_replication.c:1040]: We should probably assert here somewhere that the follower's term has updated?

**Review by MathieuBordere — APPROVED** [review]
Looks good, small remark in the test.
